### ISSUE TITLE
Incompatibility with ColdSweat 2.2

### ISSUE THREAD

**Issue by loboazul0103** [SiverDX/dragonsurvival_compatibility#1]
A lot has changed since ColdSweat updated to version 2.2, and the "Technical Changes" section seems to have introduced incompatibilities with this mod.

Here's the update history for that mode
https://www.curseforge.com/minecraft/mc-mods/cold-sweat/files/4770582

Here's the crash report
[crash-2023-09-27_10.37.36-client.txt](https://github.com/SiverDX/dragonsurvival_compatibility/files/12733278/crash-2023-09-27_10.37.36-client.txt)

**Comment by SiverDX** [comment]
Should be fixed in latest release
