### ISSUE TITLE
Crashes when dragons grow into adults (possibly an issue with ColdSweat)

### ISSUE THREAD

**Issue by loboazul0103** [SiverDX/dragonsurvival_compatibility#4]
Updating to the latest version of dragonsurvival compatibility and using the Dragon Growth item to grow into an adult dragon crashes. I don't know the exact cause, but ColdSweat seems to be mentioned in the problem.

Here is the full text of the crash

[crash-2023-12-06_21.14.14-client.txt](https://github.com/SiverDX/dragonsurvival_compatibility/files/13582756/crash-2023-12-06_21.14.14-client.txt)

**Comment by SiverDX** [comment]
should be fixed here https://legacy.curseforge.com/minecraft/mc-mods/dragon-survival-compatibility/files/4932624
