### ISSUE TITLE
mod causes softlocking on death and other issues with coldsweat.

### ISSUE THREAD

**Issue by Enatsushiroi** [SiverDX/dragonsurvival_compatibility#5]
when you die as a dragon it causes a softlock. it seems to be related to dying as an adult dragon from something like heatstroke. I can say I think it has to do with cold sweat. Changing paramaters for coldsweat also is very difficult and doesn't seem to follow the regular temperature based on 0 and I feel like the toml file needs more explaination for what numbers would actually work.

**Comment by SiverDX** [comment]
do you have a log 

regarding the attribute, cold sweat itself doesn't provide more info

**Comment by Enatsushiroi** [comment]
to my knowledge there is no way to get a log as there is no crash that occurs. It's a softlock where the respawn button just refuses to work.

**Comment by SiverDX** [comment]
that sounds like a known issue with dragon survival itself 

did you check the issues there?

latest log should still be present, shouldn't it?

**Comment by Enatsushiroi** [comment]
Here's what I found after recreating the issue. I can't tell what exactly is causing the issue, the log starts immediately after I die and am unable to respawn.

[log.txt](https://github.com/SiverDX/dragonsurvival_compatibility/files/14549895/log.txt)

**Comment by SiverDX** [comment]
yeah this is an issue with dragon survival itself
Does this still happen with this version
[dragonsurvival-1.20.1-10.03.2024.zip](https://github.com/SiverDX/dragonsurvival_compatibility/files/14549990/dragonsurvival-1.20.1-10.03.2024.zip)

**Comment by Enatsushiroi** [comment]
It seems to be working I've tried creating the circumstances that typically lead to the softlocks and they seem to be gone.
