### ISSUE TITLE
[1.20.1]Start-up Crash

### ISSUE THREAD

**Issue by ElMurlocElegante** [SiverDX/dragonsurvival_compatibility#7]
**Mod Versions:**
- Cold Sweat: 2.2.5.1
- Dragon Survival: 27.06.2024
- Dragon Survival Compability: 1.1.8

**Forge 47.3.0**
> org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: com.momosoftworks.coldsweat.util.serialization.DynamicHolder
> 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)

**Crash log**
[crash-2024-07-07_11.38.28-fml.txt](https://github.com/user-attachments/files/16119730/crash-2024-07-07_11.38.28-fml.txt)

**Comment by SiverDX** [comment]
fixed in latest release
