### ISSUE TITLE
Dragon Survival Compatibility broken 

### ISSUE THREAD

**Issue by Hoddrock** [SiverDX/dragonsurvival_compatibility#8]
this mod breaks the Dagon survival mod when the Coldsweat mod is active

[crash-2024-08-06_03.16.48-fml.txt](https://github.com/user-attachments/files/16505702/crash-2024-08-06_03.16.48-fml.txt)

**Comment by SiverDX** [comment]
use the latest version
(currently https://www.curseforge.com/minecraft/mc-mods/cold-sweat/files/5553199)
